training_data_paths:
- C:\Users\rioti\Documents\GitHub\NLP_prediction-and-forecasting\training_data_arrow\ADRIATIC_SEA.arrow
- C:\Users\rioti\Documents\GitHub\NLP_prediction-and-forecasting\training_data_arrow\ADRIATIC_SEA_no_season.arrow
- C:\Users\rioti\Documents\GitHub\NLP_prediction-and-forecasting\training_data_arrow\ADRIATIC_SEA_no_season_outside_66.arrow
- C:\Users\rioti\Documents\GitHub\NLP_prediction-and-forecasting\training_data_arrow\ADRIATIC_SEA_outside_66.arrow
- C:\Users\rioti\Documents\GitHub\NLP_prediction-and-forecasting\training_data_arrow\ANDAMAN_SEA.arrow
- C:\Users\rioti\Documents\GitHub\NLP_prediction-and-forecasting\training_data_arrow\ANDAMAN_SEA_no_season.arrow
- C:\Users\rioti\Documents\GitHub\NLP_prediction-and-forecasting\training_data_arrow\ANDAMAN_SEA_no_season_outside_66.arrow
- C:\Users\rioti\Documents\GitHub\NLP_prediction-and-forecasting\training_data_arrow\ANDAMAN_SEA_outside_66.arrow
- C:\Users\rioti\Documents\GitHub\NLP_prediction-and-forecasting\training_data_arrow\ARABIAN_SEA.arrow
- C:\Users\rioti\Documents\GitHub\NLP_prediction-and-forecasting\training_data_arrow\ARABIAN_SEA_no_season.arrow
- C:\Users\rioti\Documents\GitHub\NLP_prediction-and-forecasting\training_data_arrow\ARABIAN_SEA_no_season_outside_66.arrow
- C:\Users\rioti\Documents\GitHub\NLP_prediction-and-forecasting\training_data_arrow\ARABIAN_SEA_outside_66.arrow
- C:\Users\rioti\Documents\GitHub\NLP_prediction-and-forecasting\training_data_arrow\ATLANTIC_OCEAN.arrow
- C:\Users\rioti\Documents\GitHub\NLP_prediction-and-forecasting\training_data_arrow\ATLANTIC_OCEAN_no_season.arrow
- C:\Users\rioti\Documents\GitHub\NLP_prediction-and-forecasting\training_data_arrow\ATLANTIC_OCEAN_no_season_outside_66.arrow
- C:\Users\rioti\Documents\GitHub\NLP_prediction-and-forecasting\training_data_arrow\ATLANTIC_OCEAN_outside_66.arrow
- C:\Users\rioti\Documents\GitHub\NLP_prediction-and-forecasting\training_data_arrow\BALTIC_SEA.arrow
- C:\Users\rioti\Documents\GitHub\NLP_prediction-and-forecasting\training_data_arrow\BALTIC_SEA_no_season.arrow
- C:\Users\rioti\Documents\GitHub\NLP_prediction-and-forecasting\training_data_arrow\BALTIC_SEA_no_season_outside_66.arrow
- C:\Users\rioti\Documents\GitHub\NLP_prediction-and-forecasting\training_data_arrow\BALTIC_SEA_outside_66.arrow
- C:\Users\rioti\Documents\GitHub\NLP_prediction-and-forecasting\training_data_arrow\BAY_OF_BENGALS.arrow
- C:\Users\rioti\Documents\GitHub\NLP_prediction-and-forecasting\training_data_arrow\BAY_OF_BENGALS_no_season.arrow
- C:\Users\rioti\Documents\GitHub\NLP_prediction-and-forecasting\training_data_arrow\BAY_OF_BENGALS_no_season_outside_66.arrow
- C:\Users\rioti\Documents\GitHub\NLP_prediction-and-forecasting\training_data_arrow\BAY_OF_BENGALS_outside_66.arrow
- C:\Users\rioti\Documents\GitHub\NLP_prediction-and-forecasting\training_data_arrow\BERING_SEA.arrow
- C:\Users\rioti\Documents\GitHub\NLP_prediction-and-forecasting\training_data_arrow\BERING_SEA_no_season.arrow
- C:\Users\rioti\Documents\GitHub\NLP_prediction-and-forecasting\training_data_arrow\BERING_SEA_no_season_outside_66.arrow
- C:\Users\rioti\Documents\GitHub\NLP_prediction-and-forecasting\training_data_arrow\BERING_SEA_outside_66.arrow
- C:\Users\rioti\Documents\GitHub\NLP_prediction-and-forecasting\training_data_arrow\CARIBBEAN_SEA.arrow
- C:\Users\rioti\Documents\GitHub\NLP_prediction-and-forecasting\training_data_arrow\CARIBBEAN_SEA_no_season.arrow
- C:\Users\rioti\Documents\GitHub\NLP_prediction-and-forecasting\training_data_arrow\CARIBBEAN_SEA_no_season_outside_66.arrow
- C:\Users\rioti\Documents\GitHub\NLP_prediction-and-forecasting\training_data_arrow\CARIBBEAN_SEA_outside_66.arrow
- C:\Users\rioti\Documents\GitHub\NLP_prediction-and-forecasting\training_data_arrow\GULF_of_AMERICA.arrow
- C:\Users\rioti\Documents\GitHub\NLP_prediction-and-forecasting\training_data_arrow\GULF_of_AMERICA_no_season.arrow
- C:\Users\rioti\Documents\GitHub\NLP_prediction-and-forecasting\training_data_arrow\GULF_of_AMERICA_no_season_outside_66.arrow
- C:\Users\rioti\Documents\GitHub\NLP_prediction-and-forecasting\training_data_arrow\GULF_of_AMERICA_outside_66.arrow
- C:\Users\rioti\Documents\GitHub\NLP_prediction-and-forecasting\training_data_arrow\INDIAN_OCEAN.arrow
- C:\Users\rioti\Documents\GitHub\NLP_prediction-and-forecasting\training_data_arrow\INDIAN_OCEAN_no_season.arrow
- C:\Users\rioti\Documents\GitHub\NLP_prediction-and-forecasting\training_data_arrow\INDIAN_OCEAN_no_season_outside_66.arrow
- C:\Users\rioti\Documents\GitHub\NLP_prediction-and-forecasting\training_data_arrow\INDIAN_OCEAN_outside_66.arrow
- C:\Users\rioti\Documents\GitHub\NLP_prediction-and-forecasting\training_data_arrow\INDONESIAN.arrow
- C:\Users\rioti\Documents\GitHub\NLP_prediction-and-forecasting\training_data_arrow\INDONESIAN_no_season.arrow
- C:\Users\rioti\Documents\GitHub\NLP_prediction-and-forecasting\training_data_arrow\INDONESIAN_no_season_outside_66.arrow
- C:\Users\rioti\Documents\GitHub\NLP_prediction-and-forecasting\training_data_arrow\INDONESIAN_outside_66.arrow
- C:\Users\rioti\Documents\GitHub\NLP_prediction-and-forecasting\training_data_arrow\MEDITERRANEAN_SEA.arrow
- C:\Users\rioti\Documents\GitHub\NLP_prediction-and-forecasting\training_data_arrow\MEDITERRANEAN_SEA_no_season.arrow
- C:\Users\rioti\Documents\GitHub\NLP_prediction-and-forecasting\training_data_arrow\MEDITERRANEAN_SEA_no_season_outside_66.arrow
- C:\Users\rioti\Documents\GitHub\NLP_prediction-and-forecasting\training_data_arrow\MEDITERRANEAN_SEA_outside_66.arrow
- C:\Users\rioti\Documents\GitHub\NLP_prediction-and-forecasting\training_data_arrow\NORTH_ATLANTIC_OCEAN.arrow
- C:\Users\rioti\Documents\GitHub\NLP_prediction-and-forecasting\training_data_arrow\NORTH_ATLANTIC_OCEAN_no_season.arrow
- C:\Users\rioti\Documents\GitHub\NLP_prediction-and-forecasting\training_data_arrow\NORTH_ATLANTIC_OCEAN_no_season_outside_66.arrow
- C:\Users\rioti\Documents\GitHub\NLP_prediction-and-forecasting\training_data_arrow\NORTH_ATLANTIC_OCEAN_outside_66.arrow
- C:\Users\rioti\Documents\GitHub\NLP_prediction-and-forecasting\training_data_arrow\NORTH_PACIFIC_OCEAN.arrow
- C:\Users\rioti\Documents\GitHub\NLP_prediction-and-forecasting\training_data_arrow\NORTH_PACIFIC_OCEAN_no_season.arrow
- C:\Users\rioti\Documents\GitHub\NLP_prediction-and-forecasting\training_data_arrow\NORTH_PACIFIC_OCEAN_no_season_outside_66.arrow
- C:\Users\rioti\Documents\GitHub\NLP_prediction-and-forecasting\training_data_arrow\NORTH_PACIFIC_OCEAN_outside_66.arrow
- C:\Users\rioti\Documents\GitHub\NLP_prediction-and-forecasting\training_data_arrow\NORTH_SEA.arrow
- C:\Users\rioti\Documents\GitHub\NLP_prediction-and-forecasting\training_data_arrow\NORTH_SEA_no_season.arrow
- C:\Users\rioti\Documents\GitHub\NLP_prediction-and-forecasting\training_data_arrow\NORTH_SEA_no_season_outside_66.arrow
- C:\Users\rioti\Documents\GitHub\NLP_prediction-and-forecasting\training_data_arrow\NORTH_SEA_outside_66.arrow
- C:\Users\rioti\Documents\GitHub\NLP_prediction-and-forecasting\training_data_arrow\PACIFIC_OCEAN.arrow
- C:\Users\rioti\Documents\GitHub\NLP_prediction-and-forecasting\training_data_arrow\PACIFIC_OCEAN_no_season.arrow
- C:\Users\rioti\Documents\GitHub\NLP_prediction-and-forecasting\training_data_arrow\PACIFIC_OCEAN_no_season_outside_66.arrow
- C:\Users\rioti\Documents\GitHub\NLP_prediction-and-forecasting\training_data_arrow\PACIFIC_OCEAN_outside_66.arrow
- C:\Users\rioti\Documents\GitHub\NLP_prediction-and-forecasting\training_data_arrow\PERSIAN_GULF.arrow
- C:\Users\rioti\Documents\GitHub\NLP_prediction-and-forecasting\training_data_arrow\PERSIAN_GULF_no_season.arrow
- C:\Users\rioti\Documents\GitHub\NLP_prediction-and-forecasting\training_data_arrow\PERSIAN_GULF_no_season_outside_66.arrow
- C:\Users\rioti\Documents\GitHub\NLP_prediction-and-forecasting\training_data_arrow\PERSIAN_GULF_outside_66.arrow
- C:\Users\rioti\Documents\GitHub\NLP_prediction-and-forecasting\training_data_arrow\SEA_of_JAPAN.arrow
- C:\Users\rioti\Documents\GitHub\NLP_prediction-and-forecasting\training_data_arrow\SEA_of_JAPAN_no_season.arrow
- C:\Users\rioti\Documents\GitHub\NLP_prediction-and-forecasting\training_data_arrow\SEA_of_JAPAN_no_season_outside_66.arrow
- C:\Users\rioti\Documents\GitHub\NLP_prediction-and-forecasting\training_data_arrow\SEA_of_JAPAN_outside_66.arrow
- C:\Users\rioti\Documents\GitHub\NLP_prediction-and-forecasting\training_data_arrow\SEA_of_OKHOTSK.arrow
- C:\Users\rioti\Documents\GitHub\NLP_prediction-and-forecasting\training_data_arrow\SEA_of_OKHOTSK_no_season.arrow
- C:\Users\rioti\Documents\GitHub\NLP_prediction-and-forecasting\training_data_arrow\SEA_of_OKHOTSK_no_season_outside_66.arrow
- C:\Users\rioti\Documents\GitHub\NLP_prediction-and-forecasting\training_data_arrow\SEA_of_OKHOTSK_outside_66.arrow
- C:\Users\rioti\Documents\GitHub\NLP_prediction-and-forecasting\training_data_arrow\SOUTH_CHINA_SEA.arrow
- C:\Users\rioti\Documents\GitHub\NLP_prediction-and-forecasting\training_data_arrow\SOUTH_CHINA_SEA_no_season.arrow
- C:\Users\rioti\Documents\GitHub\NLP_prediction-and-forecasting\training_data_arrow\SOUTH_CHINA_SEA_no_season_outside_66.arrow
- C:\Users\rioti\Documents\GitHub\NLP_prediction-and-forecasting\training_data_arrow\SOUTH_CHINA_SEA_outside_66.arrow
- C:\Users\rioti\Documents\GitHub\NLP_prediction-and-forecasting\training_data_arrow\TROPICS.arrow
- C:\Users\rioti\Documents\GitHub\NLP_prediction-and-forecasting\training_data_arrow\TROPICS_no_season.arrow
- C:\Users\rioti\Documents\GitHub\NLP_prediction-and-forecasting\training_data_arrow\TROPICS_no_season_outside_66.arrow
- C:\Users\rioti\Documents\GitHub\NLP_prediction-and-forecasting\training_data_arrow\TROPICS_outside_66.arrow
- C:\Users\rioti\Documents\GitHub\NLP_prediction-and-forecasting\training_data_arrow\YELLOW_SEA.arrow
- C:\Users\rioti\Documents\GitHub\NLP_prediction-and-forecasting\training_data_arrow\YELLOW_SEA_no_season.arrow
- C:\Users\rioti\Documents\GitHub\NLP_prediction-and-forecasting\training_data_arrow\YELLOW_SEA_no_season_outside_66.arrow
- C:\Users\rioti\Documents\GitHub\NLP_prediction-and-forecasting\training_data_arrow\YELLOW_SEA_outside_66.arrow
probability:
- 0.011363636363636364
- 0.011363636363636364
- 0.011363636363636364
- 0.011363636363636364
- 0.011363636363636364
- 0.011363636363636364
- 0.011363636363636364
- 0.011363636363636364
- 0.011363636363636364
- 0.011363636363636364
- 0.011363636363636364
- 0.011363636363636364
- 0.011363636363636364
- 0.011363636363636364
- 0.011363636363636364
- 0.011363636363636364
- 0.011363636363636364
- 0.011363636363636364
- 0.011363636363636364
- 0.011363636363636364
- 0.011363636363636364
- 0.011363636363636364
- 0.011363636363636364
- 0.011363636363636364
- 0.011363636363636364
- 0.011363636363636364
- 0.011363636363636364
- 0.011363636363636364
- 0.011363636363636364
- 0.011363636363636364
- 0.011363636363636364
- 0.011363636363636364
- 0.011363636363636364
- 0.011363636363636364
- 0.011363636363636364
- 0.011363636363636364
- 0.011363636363636364
- 0.011363636363636364
- 0.011363636363636364
- 0.011363636363636364
- 0.011363636363636364
- 0.011363636363636364
- 0.011363636363636364
- 0.011363636363636364
- 0.011363636363636364
- 0.011363636363636364
- 0.011363636363636364
- 0.011363636363636364
- 0.011363636363636364
- 0.011363636363636364
- 0.011363636363636364
- 0.011363636363636364
- 0.011363636363636364
- 0.011363636363636364
- 0.011363636363636364
- 0.011363636363636364
- 0.011363636363636364
- 0.011363636363636364
- 0.011363636363636364
- 0.011363636363636364
- 0.011363636363636364
- 0.011363636363636364
- 0.011363636363636364
- 0.011363636363636364
- 0.011363636363636364
- 0.011363636363636364
- 0.011363636363636364
- 0.011363636363636364
- 0.011363636363636364
- 0.011363636363636364
- 0.011363636363636364
- 0.011363636363636364
- 0.011363636363636364
- 0.011363636363636364
- 0.011363636363636364
- 0.011363636363636364
- 0.011363636363636364
- 0.011363636363636364
- 0.011363636363636364
- 0.011363636363636364
- 0.011363636363636364
- 0.011363636363636364
- 0.011363636363636364
- 0.011363636363636364
- 0.011363636363636364
- 0.011363636363636364
- 0.011363636363636364
- 0.011363636363636364
context_length: 512
prediction_length: 64
min_past: 60
max_steps: 2000
save_steps: 100_000
log_steps: 500
per_device_train_batch_size: 32
learning_rate: 0.001
optim: adamw_torch_fused
num_samples: 20
shuffle_buffer_length: 100_000
gradient_accumulation_steps: 1
model_id: google/t5-efficient-tiny
model_type: seq2seq
random_init: false
tie_embeddings: true
output_dir: ./output/
tf32: true
torch_compile: false
tokenizer_class: MeanScaleUniformBins
tokenizer_kwargs:
  low_limit: -15.0
  high_limit: 15.0
n_tokens: 4096
lr_scheduler_type: linear
warmup_ratio: 0.0
dataloader_num_workers: 0
max_missing_prop: 0.9
use_eos_token: true
progress_bar_refresh_rate: 1
disable_tqdm: false
